version: '3.0'
services:
  mongo-db:
    image: 'mongo:3.6'
    hostname: mongo-db
    container_name: mongo-db
    expose:
      - '27017'
    ports:
      - '27017:27017'
    networks:
      - default
    command: '--bind_ip_all --smallfiles'
    volumes:
      - './mongo-db:/data'

  api-afarclolud-mongo:
    image: afarcloud/api-mongo:1.0
    hostname: api-afarcloud-mongo
    container_name: api-afarcloud-mongo
    depends_on:
      - mongo-db
    environment:
     - ENV=development
     - HOST_API=0.0.0.0
     - PORT_API=5000
    ports:
     - '${PORT_API}:${PORT_API}'
    networks:
      - default
    healthcheck:
        test: ["CMD", "curl", "-f", "http://${HOST_API}:${PORT_API}"]
        interval: 1m30s
        timeout: 10s
        retries: 3
        #start_period: 40s

volumes:
  mongo-db: 
