apiVersion: v1
kind: Service
metadata:
  name: api-afarclolud-mongo
  labels:
    run: api-mongo
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  type: NodePort
  selector:
    run: api-afarclolud-mongo
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: api-afarclolud-mongo
spec:
  template:
    metadata:
      labels:
        run: api-afarclolud-mongo
    spec:
      containers:
      - env:
        - name: ENV
          value: development
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "5000"
        image: afarcloud/api:1.0
        name: api-afarclolud-mongo
        ports:
        - containerPort: 5000
        resources: {}
      hostname: api-afarclolud-mongo
      restartPolicy: Always
status: {}

